### ISSUE TITLE
Question on the result

### ISSUE THREAD

**Issue by zhanhaoyu** [Xiaoming-Zhao/advtex_init_align#1]
Hi,
Thank you  for sharing your code. I run your code with your data but the results are different from those shown in your paper(It seems that there are blurs inside the rectangle).  Is there any advice to get better results?
Thank you!

![A65CE907-DE54-400e-92BE-8A2D6823D264](https://user-images.githubusercontent.com/80403774/191902097-1e6b3ccb-29c1-4eb2-897f-6d7c90b9cbdd.png)
![1243BA6B-AD2F-4f79-A7F3-47904448D75D](https://user-images.githubusercontent.com/80403774/191902105-060ec3f5-d135-4292-8cc1-79a8cda8e2f1.png)
![D47F8BEE-14C5-4bae-AAAC-E90A953EBE38](https://user-images.githubusercontent.com/80403774/191902107-51ce0632-f70c-4a7a-9e59-e071e4e7ca11.png)

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for your interests in this work. May I know whether these are results from the `tex_init` or the final one?

**Comment by zhanhaoyu** [comment]
These are the final one. Did you need `my tex_init`?

**Comment by Xiaoming-Zhao** [comment]
Thanks for the information. Do you mind checking how results from `tex_init` look like?

**Comment by zhanhaoyu** [comment]
[04.zip](https://github.com/Xiaoming-Zhao/advtex_init_align/files/9631193/04.zip)
Here is the result of `scene_04` , I wonder whether I run the code correctly?Thank you

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot. The `tex_init` looks reasonable to me. I will try to fine time to re-run the code this weekend to see whether there are some issues resulting from code cleaning.

In the meantime, you may want to check the intermediate results, which I think the code saves them in the folder. For example,
- L2 average texture: for filling some black areas in textures from `tex_init`
- several intermediate training results when you run `tex_smooth`

**Comment by Xiaoming-Zhao** [comment]
Hi @zhanhaoyu , I re-ran the code but did not encounter the issue you mentioned. See [the results for `scene_04`](https://github.com/Xiaoming-Zhao/advtex_init_align/files/9632629/scene_04-optimized_texture_test_1_10.zip).

However, I do find some typos. I am not sure whether they will affect it. I pushed a new commit 421a109a60e040d7c7df6f84b6ba48d582cfbeab. Maybe you can try the updated one?

Meanwhile, I would recommend running the command in `run.sh` one by one instead such that you will not miss any error messages if there are any.

**Comment by Yzhbuaa** [comment]
@zhanhaoyu Hi, I met the same problem. The texture mapping result of scene_01 is the same as your result. Did you solved it?

**Comment by zhanhaoyu** [comment]
yeah, the version of the pytorch3d could affect&nbsp;the result, after I installing the pytorch3d(version 0.4.0), the result is&nbsp;basically the same as one your paper shows.
&nbsp;


zhy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xiaoming-Zhao/advtex_init_align] Question on the result (Issue #1)





 
@zhanhaoyu Hi, I met the same problem. The texture mapping result of scene_01 is the same as your result. Did you solved it?
