### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Xiaoming-Zhao/advtex_init_align#10]
I would like to point out that identifiers like “[`__H_OURIO__`](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/ba648a9bd567b54ed62287c675263506b3026286/advtex_init_align/tex_init/OurIO.h#L1 "Update candidate")” and “[`__H_STREAM_FILE__`](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/ba648a9bd567b54ed62287c675263506b3026286/advtex_init_align/tex_init/StreamFile.h#L1 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Xiaoming-Zhao** [comment]
Hi Markus, thanks a lot for your time in spotting these issues. I have changed them to be compliant with the standards.

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
