### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Xiaoming-Zhao/advtex_init_align#11]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [MPGraph](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/ba648a9bd567b54ed62287c675263506b3026286/advtex_init_align/tex_init/Region.h#L154 "Destructor for MPGraph")
- [StreamFile::ClearData](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/ba648a9bd567b54ed62287c675263506b3026286/advtex_init_align/tex_init/StreamFile.cpp#L42 "StreamFile::ClearData function")

**Comment by Xiaoming-Zhao** [comment]
Hi Markus, thanks a lot for your time in spotting these issues.

I have modified the `StreamFile` but left `MPGraph` untouched at this time. `MPGraph` was adopted from other packages and I preferred to keep it as it is now.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by Xiaoming-Zhao** [comment]
Definitely a good suggestion Markus. I am a little bit occupied these days and will try these tools later. Thanks a lot.
