### ISSUE TITLE
Is it possible to use this method without depth map and camera extrinsics?

### ISSUE THREAD

**Issue by Ruye-aa** [Xiaoming-Zhao/advtex_init_align#13]
Hi, Xiaoming!  I hope this message finds you well. I am currently working on a project where I am attempting to apply textures from high-resolution images to a scanned 3D model. The data I have at my disposal includes a mesh model and its corresponding texture map, along with a few high-resolution detail images captured and camera intrinsic parameters.I came across the advtex_init_align method in your paper and was wondering if it could be suitable for achieving my goal.

Furthermore, I would greatly appreciate any advice or suggestions you may have regarding the process of texture mapping using high-resolution images on scanned 3D models. Your expertise in this field would be invaluable to me.

Thank you very much for your time and assistance. I look forward to your response.

Best regards

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for your interest in this work.

Unfortunately, this repo indeed requires depth and extrinsic. However, I think you could obtain these requirements from the data you already have:

1. For **extrinsics**, you could obtain them from Structure-from-Motion (SfM), a field that tackles the problem of estimating 3D structure (including camera intrinsics and extrinsic) from pure 2D RGB images. A popular toolkit is [colmap](https://github.com/colmap/colmap):

    a. Since you already have the intrinsics, you only need to estimate the extrinsics, which is supported by Colmap, see [here](https://github.com/colmap/colmap/blob/d780e1dda63aadd637f2be68f66cf15e916a5cec/doc/faq.rst#fix-intrinsics) and https://github.com/colmap/colmap/issues/1526

    b. I recommend having a double check to see whether the estimated extrinsics are good enough via projecting your 3D model with the Colmap-estimated extrinsics. I have never run Colmap with known intrinsics before but I think the results should be reasonable.

2. For **depth**: you could obtain them by running some consistent video depth (CVD) estimation algorithms. Since you are dealing with static scenes, I think it will not be hard and CVD should be able to work well. Some tools that I used before are:

    - https://github.com/facebookresearch/robust_cvd (I recommend starting from this one if you do not have much experience before as the documentation is better and there exists a demo)
    - https://github.com/google/dynamic-video-depth

**Comment by Ruye-aa** [comment]
Thank you so much for your prompt response. I'm delighted by your quick reply—it's truly amazing. I truly appreciate your valuable advice, and I will definitely give it a try. Your suggestions will be immensely helpful in my project.

Once again, thank you for your assistance and support. I am grateful for your willingness to help.

Best regards

**Comment by Xiaoming-Zhao** [comment]
No worries.

I just realize one thing:

If your 3D scan is a dense model, then you do not need to run the CVD algorithms as you could directly compute depth based on the 3D model and extrinsics.

And one caveat: the [robust-CVD](https://github.com/facebookresearch/robust_cvd) will modify extrinsics. You may want to check whether there are options that could turn this off.

Alternatively, you could try https://github.com/facebookresearch/consistent_depth, which is the prior work of robust-CVD.

Anyway, you could try several different ways and see which one fits your project better.

**Comment by Ruye-aa** [comment]
I appreciate your response and find your suggestion to be quite valuable as well. 

Interestingly, prior to coming across your paper, I was attempting a manual approach where I had to manually mark corresponding points on the 3D model and the images for texture mapping. I referred to a paper called "[FlexiStickers – Photogrammetric Texture Mapping using Casual Images](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=8ae779d4af54a35ea297f2f5cd45d17c16105f3c)," which is more than a decade old. However, due to the lack of available code, I found it challenging to implement their method effectively.

While I still have some reservations about the achievable accuracy using advtex_init_align, I will definitely give it a try as you suggested. I believe it's worth exploring and evaluating its performance for my project.

Thank you once again for your prompt response and the insight you provided. I truly appreciate your assistance.

**Comment by Ruye-aa** [comment]
I wanted to mention that our motivation for pursuing the manual marking approach was primarily focused on texturing specific, locally important areas rather than the entire large-scale scene. I understand that this differs from the original intention of your paper, but your work still provided me with significant inspiration and guidance.
