### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: mtl0.png

### ISSUE THREAD

**Issue by lw0210** [Xiaoming-Zhao/advtex_init_align#2]
Dear,
Excuse me ! When I run your code through the command you provide: "bash ${CODE_ROOT}/run.sh\
${CODE_ROOT} \
${SCENE_ID} \
run_ Train " .
After running for a while, an error message appears," No such file or directory: '....../advtex_init_align/experiments/scene_04/test_1_1_0/optim/unary_1024_1024_atlas_60/fused/shape/mtl0. png' "  I checked that the shape folder is empty.How can I solve this problem？

**Comment by Xiaoming-Zhao** [comment]
Hi, I think it may be due to that some steps in the `run.sh` fail. To understand which steps have issues, you can run the `run.sh` command by command. Namely, every time you can run only one command and comment out the other. Hope this helps.

**Comment by lw0210** [comment]
OK,Thanks！I&nbsp; will try it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiaoming-Zhao/advtex_init_align"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 凌晨4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiaoming-Zhao/advtex_init_align] FileNotFoundError: [Errno 2] No such file or directory: mtl0.png (Issue #2)





 
Hi, I think it may be due to that some steps in the run.sh fail. To understand which steps have issues, you can run the run.sh command by command. Namely, every time you can run only one command and comment out the other. Hope this helps.
