### ISSUE TITLE
How to run on scannet dataset？

### ISSUE THREAD

**Issue by lw0210** [Xiaoming-Zhao/advtex_init_align#3]
Dear，
I  have successfully run the command in your readme.However, how can I get the running results on the scannet dataset as shown in your paper？（I have downloaded this dataset）

And , how can I get the results of quantitative evaluation as shown in your paper？

**Comment by Xiaoming-Zhao** [comment]
Sorry for the late reply. I just added scripts for running on ScanNet in #6.

Regarding the quantitative evaluation, the README states how to obtain them.

Hope this helps.
