### ISSUE TITLE
Without aligned depth Images

### ISSUE THREAD

**Issue by satyajitghana** [Xiaoming-Zhao/advtex_init_align#4]
Hi,

I have a use-case where i have images, which are not exactly aligned with the mesh. I want to align these images to the mesh so that the texture that comes is sharp and good. But from your approach i think i need the aligned depth along with the image. 

Is there a possibility for my use case to work ?

**Comment by Xiaoming-Zhao** [comment]
Hi Satyajit, sorry for the late response.

Yes, this work requires a depth map for each RGB image. You may consider using some works of consistent depth estimation to get consistent depth across all frames.

Hope this helps.
