### ISSUE TITLE
How to run on custom data?

### ISSUE THREAD

**Issue by Woolseyyy** [Xiaoming-Zhao/advtex_init_align#5]
Hi, appreciate for your great work!
I am trying to run with my custom data by transfrom the data into "extracted" formate, i.e., mesh.ply, depth, mat and rgb. However, when I run the code, it seems that Recv.stream in the raw dataset is also needed. What's Recv.stream? Do you have any suggestions?

**Comment by Xiaoming-Zhao** [comment]
Hi Haoqian, I added a script to convert from ScanNet's data format to the format we are using: 
https://github.com/Xiaoming-Zhao/advtex_init_align/blob/58c86ed7a8a9e585fc7949fee8f40143e68c0135/run_scannet.sh#L87

Meanwhile, you can take a look at the binary file reader to get a sense how we store the data:
https://github.com/Xiaoming-Zhao/advtex_init_align/blob/58c86ed7a8a9e585fc7949fee8f40143e68c0135/advtex_init_align/utils/stream_utils.py#L355

Essentially, we store in the order of `[RGB1, depth1, view_mat1, proj_mat1, RGB2, ...] `.

Hope this helps.

**Comment by Woolseyyy** [comment]
> Hi Haoqian, I added a script to convert from ScanNet's data format to the format we are using, which may give you some senses:
> 
> https://github.com/Xiaoming-Zhao/advtex_init_align/blob/58c86ed7a8a9e585fc7949fee8f40143e68c0135/run_scannet.sh#L87
> 
> Meanwhile, you can take a look at the binary file reader to get a sense how we store the data:
> 
> https://github.com/Xiaoming-Zhao/advtex_init_align/blob/58c86ed7a8a9e585fc7949fee8f40143e68c0135/advtex_init_align/utils/stream_utils.py#L355
> 
> Essentially, we store in the order of `[RGB1, depth1, view_mat1, proj_mat1, RGB2, ...] `.
> 
> Hope this helps.

Thank you! I am working on it.
