### ISSUE TITLE
Textinit crashed when run on the custom data.

### ISSUE THREAD

**Issue by Woolseyyy** [Xiaoming-Zhao/advtex_init_align#8]
As you know, I am trying to run the repo on my own data. Here is the overall steps of my data processing.
Step 0, I prepare the [data](https://www.dropbox.com/scl/fo/kiss2kb861ptmdyzujfja/h?dl=0&rlkey=094k49j702k44w63asc4y9wt5) in the "extracted" formate and check them with the provided [notebook](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/main/advtex_init_align/data/demo.ipynb). 

Step 1, I write a bin_data_writer.py according to [bin_data_reader.py](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/main/advtex_init_align/data/bin_data_reader.py) to transform the data in "raw" formate, which includes "Recv.stream", "Vertices.0" and "Faces.0". I check the transformed data by  extracting them back with [bin_data_reader.py](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/main/advtex_init_align/data/bin_data_reader.py) and [notebook](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/main/advtex_init_align/data/demo.ipynb). [Here ](https://www.dropbox.com/scl/fo/p9lgdngbxm9grdd14tud7/h?dl=0&rlkey=4bxotrixbn99v21sa51eb1n1l)is the data.

Step 2, I split the mesh using [command in run_scannet.sh](https://github.com/Xiaoming-Zhao/advtex_init_align/blob/2f30b94090d4f04ea740b4c21a19dfb2e73328cb/run_scannet.sh#L106-L117). And then, I replace "Vertices.0" and "Faces.0" with splited sub meshes. [Here ](https://www.dropbox.com/scl/fo/vbs1gbj6d7glizhxfbdxn/h?dl=0&rlkey=zz9lhx1kr723vf5ba3se3tgju)is the data.

However, when run training, it crashed at "Start resolving TexTriangle overlapping with MP ...", the error log is:
```
[1(idx 0)/30] ... find 10100684 overlaps from 39268/39552 triangles (max 1879) in 53347 ms
[1(idx 0)/30] Start resolving TexTriangle overlapping with MP ...
tex_init: OurMeshData.cpp:1394: void NS_MeshData::OurMeshData::ResolveOverlappedConformalMap(NS_MPSolver::MPSolver<float, int>&, const int&, const int&, const string&): Assertion `MP.CheckGraph(nExpextedRegions, nExpextedLamdaSize, globalDebugFlag, prompt)' failed.
/root/Projects/advtex_init_align/run.sh: line 83:   217 Aborted                 (core dumped) ${MRF_BIN} --data_dir ${EXP_DIR}/${SCENE_ID}/${DIR_PREFIX}_1_${sample_freq} --debug 0 --debug_mesh_shape 0 --align_arg_max ${UNARY} --n_iter_mp ${N_ITERS_MP} --n_workers 10 --mtl_width ${MTL_RES} --mtl_height ${MTL_RES} --n_extrude_pixels 0 --iter_subdiv ${N_SUBDIV} --stream_type 1 --unary_potential_dummy ${DUMMY_PENALTY} --remesh 0 --bin_pack_type 3 --n_areas_per_plate_bin_pack 500 --debug_mesh_shape 0 --conformal_map 1 --compact_mtl 1 --top_one_mtl 1 --penalty_face_area ${FACE_AREA_PENALTY} --penalty_face_cam_dist ${DEPTH_PENALTY} --penalty_face_v_perception_consist ${PERCEPT_PENALTY} --pair_potential_mp 1 --pair_potential_off_diag_scale_depth 0 --pair_potential_off_diag_scale_percept 0

... done running MRF
```

Any suggestion would help!

**Comment by Xiaoming-Zhao** [comment]
Just in case, what `stream_type` you are using when running `tex_init`? For customized, they need to be `2`. See 
https://github.com/Xiaoming-Zhao/advtex_init_align/blob/2f30b94090d4f04ea740b4c21a19dfb2e73328cb/run_scannet.sh#L116

https://github.com/Xiaoming-Zhao/advtex_init_align/blob/2f30b94090d4f04ea740b4c21a19dfb2e73328cb/run_scannet.sh#L133

**Comment by Xiaoming-Zhao** [comment]
My suggestion is the following:
1. Modify `convert_scannet_to_apple_stream.py` such that it can convert your data to Apple stream. I think only minor modifications need to be made as that script just converts RGB, depth, and camera matrices on disk into the Apple stream format.
2. Use `run_scannet.sh` to process your data while **commenting out the following command** because you do not use the `*.sens` file ScanNet uses:
https://github.com/Xiaoming-Zhao/advtex_init_align/blob/2f30b94090d4f04ea740b4c21a19dfb2e73328cb/run_scannet.sh#L72-L80
